baseurl = "https://daemonza.github.io"

# Copyright
copyright = "(c) 2017 Werner Gillmer"

# Language
languageCode = "en-EN"

# Metadata format
# "yaml", "toml", "json"
metaDataFormat = "yaml"

# Theme to use (located in /themes/THEMENAME/)
theme = "hugo-redlounge"

# Enable syntax highlights
pygmentsuseclasses = true

# Pagination
paginate = 10
paginatePath = "page"

# Enable Disqus integration
disqusShortname = "daemonza-github-io"

[permalinks]
    post = "/:year/:month/:day/:slug/"
    code = "/:slug/"

[taxonomies]
    tag = "tags"
    topic = "topics"

[author]
    name = "Werner Gillmer"
    email = "werner.gillmer@gmail.com"

[params]
    sidebartitle = "Daemonza"
    sidebartagline = "clouds and stuff and bits and bobs"

    # Sidebar position
    # false, true, "left", "right"
    sidebar = "left"

    # Text for the top menu link, which goes the root URL for the site.
    # Default (if omitted) is "Home".
    home = "home"

    # Select a syntax highight.
    # Check the static/css/highlight directory for options.
    highlight = "default"

    # Google Analytics.
    gaid = "UA-11463637-6"

    # Sidebar RSS link: will only show up if there is a RSS feed
    # associated with the current page
    rss = true


[[menu.social]]
	pre = "<i class='fa fa-twitter'></i>"
    url = "https://twitter.com/daemonza"
    identifier = "twitter"

[[menu.social]]
    pre = "<i class='fa fa-github'></i>"
    url = "https://github.com/daemonza"
    identifier = "github"

[[menu.social]]
    pre = "<i class='fa fa-linkedin'></i>"
    url = "https://nl.linkedin.com/in/werner-gillmer-202a79"
    identifier = "linkedin"

